env:
  global:
    - RUST_BACKTRACE=1
    - PATH=$PATH:$HOME/.cargo/bin
os:
  - linux
  - osx
  - windows
language: rust
rust:
  - stable
  - nightly
sudo: required
addons:
    apt:
        packages:
            - libssl-dev
cache:
  cargo: true

before_script: |
  if [ "${TRAVIS_OS_NAME}" != windows ]; then
    if [ "${TRAVIS_RUST_VERSION}" == nightly ]; then
      rustup component add rustfmt;
    fi
    if [ "${TRAVIS_RUST_VERSION}" == stable ]; then
      rustup component add clippy;
    fi
  fi
before_cache: |
  if [ "${TRAVIS_OS_NAME}" == linux ]; then
    cargo install cargo-tarpaulin -f
  fi

script: |
  set -x;
  if [ "${TRAVIS_OS_NAME}" != windows ]; then
    if [ "${TRAVIS_RUST_VERSION}" == nightly ]; then
      cargo fmt -- --check
    fi &&
    if [ "${TRAVIS_RUST_VERSION}" == stable ]; then
      cargo clippy --all-targets
    fi
  fi &&
  cargo test --release --verbose

after_success: |
  if [ "${TRAVIS_OS_NAME}" == linux ] && [ "${TRAVIS_RUST_VERSION}" == stable ]; then
    # Coveralls
    cargo tarpaulin --ciserver travis-ci --coveralls $TRAVIS_JOB_ID
  fi
